version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DANGEROUSLY_SKIP_PERMISSIONS=true
      - NODE_ENV=development
      - VITE_ENV=development
    command: sleep infinity
    network_mode: host
    privileged: true

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ocma
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "54322:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data: